# Ticket Received Confirmation Email Template

## Purpose

To acknowledge a customer's support request and confirm that a support ticket has been created.

## When to Use

- Customer submits a support request
- Customer reports a technical issue
- Customer requests assistance with an account, order, or service

## Template

Subject: We’ve Received Your Support Request (Ticket #[Ticket Number])

Hello [Customer Name],

Thank you for contacting [Company Name].

We have successfully received your request and created a support ticket for your issue.

Ticket Details

- Ticket Number: #[Ticket Number]
- Issue Summary: [Brief Description of Issue]

Our support team is currently reviewing your request and will respond within 24 hours.

You can track the status of your ticket here:

[Ticket Tracking Link]

If you have additional information that may help us investigate the issue, please reply to this email.

We appreciate your patience and will work to resolve this as quickly as possible.

Kind regards,

Customer Support Team

## Notes

- Ensure the ticket number is automatically generated by the support system.
- Update response times according to company SLA requirements.
- Include a tracking link if available.